# Use lightweight Java 21 runtime
FROM amazoncorretto:21-alpine

# Set working directory inside container
WORKDIR /app

# Copy the JAR generated by Maven
COPY target/*.jar app.jar

# Expose application port
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
